---

- name: Installing and configuring Docker 
  hosts: all
  sudo: yes
  roles:
    - { role: docker, tags: ["docker"] }

- name: Setting up Rancher Server
  hosts: "rancher"
  sudo: yes
  roles:
    - { role: rancher, tags: ["rancher"] }
  
- name: Register Rancher Hosts
  hosts: "nodes"
  sudo: yes
  roles:
    - { role: rancher_reg, tags: ["rancher_reg"] }

