---

mysql_root_password: "secret pass"
mysql_host: 127.0.01 
mysql_port: 3306

# Wordpress variables
wordpress_db_name: wordpress
wordpress_db_user: wpuser
wordpress_db_password: "{{ lookup('password', wordpress_password_tmpfile + ' length=20 chars=ascii_letters,digits') }}"
wordpress_password_tmpfile: /tmp/wppasswd.file
wordpress_version: latest
wordpress_auth_key: 'z@S&~Qpaxzad%&k: <y+fIE0ri?mI:kYr#]Uj+|RskWs]7r06H+ik]7>d8y9IiIe'
wordpress_secure_auth_key: '^;4y*F!mPuz#!JYns|QEE/BaJs[Pdh1a:ry!rB|l-(yaYRd;JgY~BIp|dB]7Qo&Z'
wordpress_logged_in_key: '0R7ZF#P(%E~#5q+H;d^wQ#A!f7 29GOzEW2|8<&9K_HUxVR#r$|RdsF/(5Pv@t#h'
wordpress_nonce_key: '~7}1$|O%7AU} P{Sys#d3G-]QZ;=4lDgF0Jn<m}UEXG:M|}PoD)*NbJDf#_}).F]'
wordpress_auth_salt: 'Zg@ru_i)ih8#YmGm%T?HmC_YmL:>);la{>[gDf] a>#;-A|Y|Q{?_XuL5(^Rx#(T'
wordpress_secure_auth_salt: '}/sasZG#B_%gJ~X[<|Iy5AfYv%{I/+<i|LyCVYDH+**|iRzUszv<B6|kT|3 XSQs'
wordpress_nonce_salt: 'd!B*U28x!:)b2DF~]$hq+=iU)ZmuhDfC_{H}eN0h)6L}JNpa|Ihuo_+9Z)fQj!+B'
wordpress_loggedin_salt: 'tc4x!/P:gQj{G>l|%:sx.Oh^!]Nb0y;onKawWlmR2fYd<5GT :-kg8hR0j|_TlC*'
